export const URL_MAP = {
  BASE_URL: '',
  LOGIN: 'landing',
  HOME: 'home',
  DETAILSPAGE: 'DetailsPage',
  SIGNUP: 'signup',
  FAVORITES: 'Favorites',
  CHATS: 'Chats',
  JOBS: 'Jobs ',
  NOTIFICATION: 'Notification',
  FORGOTPASSWORD: 'Forgot_Password',
  MYACCOUNT: 'My_Account',
  CHANGEPASSWORD: 'change-password',
  CREATEJOB: 'create-job',
  PROVIDERDASHBOARD: 'Dashboard',
  PAYMENT: 'Payment',
  VERIFYMOBILE: 'Verify_mobile',
  SIGNINUSER: 'login',
  HELP: 'help',
  SERVICES: "Services",
  ADMIN_SETTINGS: 'Settings',
  ADMIN_MEMBERS: 'Members',
  ADMIN_JOB_ORDER: "Job_Orders",
  FAQ: "FaQ",
  PRIVACY: 'Privacy',
  TERMS: 'Terms',
  VERIFYEMAIL: 'verifyemail',
  PAYMENTSUCCESS: 'payment_success'
}
